---
- hosts: all
  become: yes
  vars:
    pkg_mgr: apt  # Set 'dnf' for RHEL/CentOS/Fedora, 'apt' for Ubuntu/Debian

  tasks:
    # --- Deploy the web server ---
    - name: Install Apache web server
      package:
        name: "{{ 'httpd' if pkg_mgr == 'dnf' else 'apache2' }}"
        state: present
      when: deploy_webserver

    - name: Start and enable Apache service
      service:
        name: "{{ 'httpd' if pkg_mgr == 'dnf' else 'apache2' }}"
        state: started
        enabled: yes
      when: deploy_webserver

    - name: Open port 8080 on the firewall (RHEL/CentOS/Fedora)
      firewalld:
        port: 8080/tcp
        state: enabled
        permanent: yes
      when: deploy_webserver and pkg_mgr == 'dnf'

    - name: Open port 8080 on the firewall (Ubuntu/Debian)
      ufw:
        rule: allow
        port: 8080
        proto: tcp
        state: enabled
      when: deploy_webserver and pkg_mgr == 'apt'

    - name: Deploy hello_world.html on VM1 and VM2
      template:
        src: templates/hello_world.html.j2
        dest: /var/www/html/hello_world.html
      notify:
        - Restart Apache
      when: deploy_webserver

    # --- Undeploy the web server ---
    - name: Stop and disable Apache service
      service:
        name: "{{ 'httpd' if pkg_mgr == 'dnf' else 'apache2' }}"
        state: stopped
        enabled: no
      when: undeploy_webserver

    - name: Remove Apache web server
      package:
        name: "{{ 'httpd' if pkg_mgr == 'dnf' else 'apache2' }}"
        state: absent
      when: undeploy_webserver

    - name: Close port 8080 on the firewall (RHEL/CentOS/Fedora)
      firewalld:
        port: 8080/tcp
        state: disabled
        permanent: yes
      when: undeploy_webserver and pkg_mgr == 'dnf'

    - name: Close port 8080 on the firewall (Ubuntu/Debian)
      ufw:
        rule: deny
        port: 8080
        proto: tcp
        state: enabled
      when: undeploy_webserver and pkg_mgr == 'apt'

    - name: Remove hello_world.html file
      file:
        path: /var/www/html/hello_world.html
        state: absent
      when: undeploy_webserver

  handlers:
    # Restart Apache if the HTML page is deployed or changed
    - name: Restart Apache
      service:
        name: "{{ 'httpd' if pkg_mgr == 'dnf' else 'apache2' }}"
        state: restarted

